### ISSUE TITLE
Main ideas

### ISSUE THREAD

**Issue by ctibord** [ctibord/mathoperations#1]
- [x] Digit sum
- [x] Digit count
- [x] Factorial
- [x] Fibonacci number
- [x] Sum / Subtract / Multiplication
- [x] Multi use division function (real / integers / modulo)
- [x] Tests
- [x] Pow

Anyone to help?

**Comment by jarkakr** [comment]
I will do digit sum and factorial. Assign me, please.

**Comment by ctibord** [comment]
Alright, done
